### ISSUE TITLE
脚本无法安装，是我的方法不对，还是安装链接有问题。

### ISSUE THREAD

**Issue by 8267020** [gkd-kit/network-extension#1]
https://github.com/gkd-kit/network-extension/raw/main/dist/network-extension.user.js   这个安装地址，一直是无法显示网页！

**Comment by lisonge** [comment]
因为你的梯子不能访问这个网页

**Comment by lisonge** [comment]
增加了其它安装源

- from github [network-extension.user.js](https://github.com/gkd-kit/network-extension/raw/main/dist/network-extension.user.js)

- from fastly jsdelivr [network-extension.user.js](https://fastly.jsdelivr.net/gh/gkd-kit/network-extension@main/dist/network-extension.user.js)

- from cdn jsdelivr [network-extension.user.js](https://cdn.jsdelivr.net/gh/gkd-kit/network-extension@main/dist/network-extension.user.js)
